services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db

volumes:
  postgres_volume:
